# Generated by Django 4.1.1 on 2022-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="open_bid",
            field=models.BooleanField(default=True),
        ),
    ]
