# Generated by Django 4.1.1 on 2022-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True, default="No Category Listed", max_length=24
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
