# Generated by Django 4.1.1 on 2022-09-24 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="own_goods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
